# Generated by Django 5.1.3 on 2024-12-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите пользователя",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
