# Generated by Django 5.1.3 on 2024-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
